version: '3.4'
services:
  db16:
    image: postgres:14
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo15@Elblasy     
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo15:
    image: odoo:15
    user: root
    depends_on:
      - db15
    ports:
      - "10015:8069"
      - "20015:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db15
      - USER=odoo
      - PASSWORD=odoo15@Elblasy
    volumes:
      #- /etc/timezone:/etc/timezone:trt
      #- /etc/localtime:/etc/localtime:trt
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    
